version: '3.9'

services:

  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    networks:
      - guacnet

  db:
    image: mariadb:11
    container_name: guac-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: CAMBIA_ROOT_PASS
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole
      MYSQL_PASSWORD: CAMBIA_GUAC_PASS
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - guacnet

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    restart: unless-stopped
    depends_on:
      - guacd
      - db
    environment:
      GUACD_HOSTNAME: guacd

      MYSQL_HOSTNAME: db
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole
      MYSQL_PASSWORD: CAMBIA_GUAC_PASS

    expose:
      - "8080"

    networks:
      - guacnet

  nginx:
    image: nginx:alpine
    container_name: guac-nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/certs:ro
    depends_on:
      - guacamole
    networks:
      - guacnet

networks:
  guacnet:
